name: CI
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Build module and update docs
        shell: pwsh
        run: .\build.ps1 Docs -Bootstrap
      - run: sudo apt-get install pngquant
      - run: pip install git+https://joshooaj:${GH_TOKEN}@github.com/joshooaj/mkdocs-material-insiders.git@custom
      - run: mkdocs gh-deploy --force
env:
  GH_TOKEN: ${{ secrets.MKDOCS_MATERIAL_INSIDERS }}
