name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
      - name: Publish to PSGallery
        shell: pwsh
        run: .\build.ps1 Publish -Bootstrap
env:
  PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_TOKEN }}
