name: PublishDocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  PublishDocs:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: sudo apt-get install pngquant
      - run: pip install git+https://joshooaj:${{ secrets.MKDOCS_MATERIAL_INSIDERS }}@github.com/joshooaj/mkdocs-material-insiders.git@custom
      - name: Deploy Docs
        shell: pwsh
        run: .\build.ps1 DeployDocs -Bootstrap
env:
  PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_TOKEN }}
  CI: true
